"""

Revision ID: a771848dbc7b
Revises: 50a8e78baf49
Create Date: 2023-12-25 14:40:03.110282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a771848dbc7b'
down_revision: Union[str, None] = '50a8e78baf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'price')
    # ### end Alembic commands ###
