version: "3.9"

networks:
  internal_nw:
    name: internal_nw
    driver: bridge

services:
  database:
    container_name: database-node
    image: cockroachdb/cockroach:v22.2.0
    hostname: db
    command: start-single-node --insecure --http-addr 0.0.0.0
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - ./sql/seed:/sql-seed
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - internal_nw

  broker:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-node
    hostname: broker
    ports:
      - 0.0.0.0:5672:5672
      - 0.0.0.0:15672:15672
    volumes:
      - "./config/test_setup.sh:/dev/test_setup.sh"
      - "./config/definitions.json:/etc/rabbitmq/definitions.json"
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODE_IP_ADDRESS=0.0.0.0
      - NODE_IP_ADDRESS=0.0.0.0
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit loopback_users "none"
    command: >
      sh -c "rabbitmq-server"
    networks:
      - internal_nw

  api:
    image: python:3.9.18-slim
    container_name: investor-bulletin-api
    depends_on:
      - database
      - broker
    ports:
      - "8000:8000"
    volumes:
      - "../phase_3/investor_bulletin:/app/server"
      - "../requirements.txt:/app/requirements.txt"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/server
    networks:
      - internal_nw
    command:
      - /bin/sh
      - -c
      - |
        pip3 install -r app/requirements.txt
        cd ./app/server
        alembic upgrade head
        python3 ./api/main.py

  worker:
    image: python:3.9.18-slim
    container_name: investor-bulletin-worker
    depends_on:
      - database
      - broker
    volumes:
      - "../phase_3/investor_bulletin:/app"
      - "../requirements.txt:/app/requirements.txt"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    networks:
      - internal_nw
    command:
      - /bin/sh
      - -c
      - |
        pip3 install -r app/requirements.txt
        cd ./app
        alembic upgrade head
        cd ./worker
        celery -A app worker --concurrency=1 --loglevel=INFO

  subscriber:
    image: python:3.9.18-slim
    container_name: investor-bulletin-subscriber
    depends_on:
      - database
      - broker
    volumes:
      - "../phase_3/investor_bulletin:/app"
      - "../requirements.txt:/app/requirements.txt"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    networks:
      - internal_nw
    command:
      - /bin/sh
      - -c
      - |
        pip3 install -r app/requirements.txt
        cd ./app
        alembic upgrade head
        python3 ./event_subscriber/main.py

  beat:
    image: python:3.9.18-slim
    container_name: investor-bulletin-beat
    depends_on:
      - database
      - broker
    volumes:
      - "../phase_3/investor_bulletin:/app"
      - "../requirements.txt:/app/requirements.txt"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    networks:
      - internal_nw
    command:
      - /bin/sh
      - -c
      - |
        pip3 install -r app/requirements.txt
        cd ./app
        alembic upgrade head
        cd ./worker
        celery -A app beat --loglevel=INFO
